entry-pipeline:
  delay: "100"
  source:
    otel_trace_source:
      port: 21890
      ssl: false
      authentication:
        unauthenticated:
  sink:
    - pipeline:
        name: "raw-pipeline"
    - pipeline:
        name: "service-map-pipeline"

raw-pipeline:
  source:
    pipeline:
      name: "entry-pipeline"
  buffer:
    bounded_blocking:
      buffer_size: 512
      batch_size: 64
  processor:
    - otel_trace_raw:
    - otel_trace_group:
        hosts: ["https://opensearch:9200"]
        insecure: true
        username: "admin"
        password: "admin"
  sink:
    - opensearch:
        hosts: ["https://opensearch:9200"]
        insecure: true
        username: "admin"
        password: "admin"
        index_type: trace-analytics-raw

service-map-pipeline:
  delay: "100"
  source:
    pipeline:
      name: "entry-pipeline"
  processor:
    - service_map_stateful:
        windows_duration: 100
  sink:
    - opensearch:
        hosts: ["https://opensearch:9200"]
        insecure: true
        username: "admin"
        password: "admin"
        index_type: trace-analytics-service-map

otel-logs-pipeline:
  workers: 1
  delay: "100"
  buffer:
    bounded_blocking:
      buffer_size: 512
      batch_size: 64
  source:
    otel_logs_source:
      port: 21892
      ssl: false
      authentication:
        unauthenticated:
  sink:
    - opensearch:
        hosts: ["https://opensearch:9200"]
        insecure: true
        username: "admin"
        password: "admin"
        bulk_size: 10
        index_type: custom
        index: otel-v1-logs-%{YYYY.ww}
        number_of_replicas: 0

otel-metrics-pipeline:
  source:
    otel_metrics_source:
      port: 21891
      ssl: false
      authentication:
        unauthenticated:
  processor:
    - otel_metrics_raw_processor:
  sink:
    - opensearch:
        hosts: ["https://opensearch:9200"]
        insecure: true
        username: "admin"
        password: "admin"
        bulk_size: 10
        index_type: custom
        index: otel-v1-metrics-%{YYYY.ww}
        number_of_replicas: 0