services:
  telemetry_api:
    build: 
      context: ../SampleStack.Telemetry.Api/
      dockerfile: ./Dockerfile
    container_name: ${API_HOST}
    hostname: ${API_HOST}
    env_file: env_file.env  
    ports:
      - ${API_HTTP_PORT}:${API_HTTP_PORT}
    depends_on:
      - opensearch

  telemetry_app:
    build: 
      context: ./
      dockerfile: ./Dockerfile
    container_name: ${TELEMETRY_APP_HOST}
    hostname: ${TELEMETRY_APP_HOST}
    env_file: env_file.env
    environment:
      - ConnectionStrings__OpenTelemetry=${OTEL_COLLECTOR_URL}
    depends_on:
      - telemetry_api

  otel_collector:
    image: otel/opentelemetry-collector:0.118.0
    container_name: ${OTEL_COLLECTOR_HOST}
    hostname: ${OTEL_COLLECTOR_HOST}
    env_file: env_file.env
    restart: unless-stopped
    ports:
      - ${OTEL_COLLECTOR_GRPC_PORT}:${OTEL_COLLECTOR_GRPC_PORT}
      - ${OTEL_COLLECTOR_HTTP_PORT}:${OTEL_COLLECTOR_HTTP_PORT}
    volumes:
      - ./Infrastructure/collector-config.yaml:/etc/otelcol/config.yaml
    depends_on:
      - data_prepper

  data_prepper:
    image: opensearchproject/data-prepper:2.6.1
    container_name: ${DATA_PREPPER_HOST}
    hostname: ${DATA_PREPPER_HOST}
    env_file: env_file.env 
    restart: unless-stopped
    ports:
      - ${DATA_PREPPER_HTTP_PORT}:${DATA_PREPPER_HTTP_PORT}
      - ${DATA_PREPPER_PIPELINE_PORT}:${DATA_PREPPER_PIPELINE_PORT}
      - ${DATA_PREPPER_METRICS_PORT}:${DATA_PREPPER_METRICS_PORT}
      - ${DATA_PREPPER_LOGS_PORT}:${DATA_PREPPER_LOGS_PORT}
    volumes:
      - ./Infrastructure/dataprepper-pipelines.yaml:/usr/share/data-prepper/pipelines/pipelines.yaml
    depends_on:
      - opensearch
  
  opensearch:
    image: opensearchproject/opensearch:2.11.1
    container_name: opensearch
    hostname: opensearch
    env_file: env_file.env
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - "http.cors.enabled=true"
      - "http.cors.allow-origin=*"
      - "http.cors.allow-headers=X-Requested-With, Content-Type, Content-Length, Authorization"
      - "http.cors.allow-methods=OPTIONS, HEAD, GET, POST, PUT, DELETE"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - ${OPENSEARCH_REST_PORT}:${OPENSEARCH_REST_PORT}
      - ${OPENSEARCH_ANALYSER_PORT}:${OPENSEARCH_ANALYSER_PORT}
    volumes:
      - ./data:/usr/share/opensearch/data

  opensearch_dashboards:
    image: opensearchproject/opensearch-dashboards:2.11.1
    container_name: ${DASHBOARDS_HOST}
    hostname: ${DASHBOARDS_HOST}
    env_file: env_file.env  
    restart: unless-stopped
    ports:
      - ${OPENSEARCH_DASHBOARDS_PORT}:${OPENSEARCH_DASHBOARDS_PORT}
    depends_on:
      - opensearch